services:
  nginx-spa:
    build: nginx-spa
    volumes:
      - ./nginx-spa/nginx/:/etc/nginx/
      - ./nginx-spa/public/config.js:/data/www/config.js
    ports:
      - 5000:80
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
