name: Testing

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: powershell

  powershell-devop-tools:
    if: fromJSON(needs.should-run.outputs.result)['powershell'] == 'true'
    runs-on: ubuntu-latest
    needs: should-run
    defaults:
      run:
        working-directory: powershell
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
      - name: Running tests
        shell: pwsh
        run: Invoke-Pester -Path .\tests\ -Output Detailed
