name: Running tests

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: powershell

  powershell-devop-tools:
    if: fromJSON(needs.should-run.outputs.result)['powershell'] == 'true'
    runs-on: windows-latest
    needs: should-run
    strategy:
      matrix:
        as_admin: [true, false]
    defaults:
      run:
        working-directory: powershell
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Running tests (admin = ${{ matrix.as_admin }})
        run: .\pester.ps1 -AsAdmin:$${{ matrix.as_admin }}
